version: '3'

networks:
  db:
    external: false

services:
  db:
    image: 'postgres:12-alpine'
    restart: 'always'
    networks:
      - db
    ports:
      - "5433:5432" # Alternative port so it won't conflict if you have a local PostgreSQL
    environment:
      POSTGRES_DB: gasgo
      POSTGRES_USER: gasgo_user
      POSTGRES_PASSWORD: gasgo_password
    volumes:
      - ./database/postgresql/scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

